Fix/small optimizations
redkubes/otomi pull request #9
Opened 2020-11-27 11:30 UTC by svatwork

In the setup.md file I found some improvements. AWS is obvious, the actual command is different. 

On my host, anyway, --rm is useful to not spawn too many containers.

2020-11-27 14:21 UTC, Morriz approved these changes

2020-11-30 13:23 UTC, svatwork reviewed
Does it make sense to paste the content over here? I am in doubt whether it would be better to put it before the configuration page.

2020-11-30 15:53 UTC, Morriz requested changes
I like the additions, but you made some wrong assumptions. Please read my feedback

2020-11-30 15:53 UTC, Morriz commented on docs/inst-deployment.md
> +If you have not done so already, put the pullsecret you have been given in `secrets.settings.yaml` under `otomi.pullSecret`. Make sure the git details are correctly added to 'charts/\*otomi-api.yaml'
I would rewrite the part about access tokens, as that is optional...but it might be worth noting:
```
Remember that some providers like GitHub need an access token (e.g. https://github.com/settings/tokens) so provide that as value for the 'password' key below.
```

2020-11-30 15:53 UTC, Morriz commented on docs/inst-deployment.md
> +If you have not done so already, put the pullsecret you have been given in `secrets.settings.yaml` under `otomi.pullSecret`. Make sure the git details are correctly added to 'charts/\*otomi-api.yaml'
can you use backticks for file names? So `charts/*otomi-api.yaml`

2020-11-30 15:53 UTC, Morriz commented on docs/inst-deployment.md
> +## Start Otomi Console on your local machine (optional)
why is this "Start Otomi Console" part transported to this `docs/inst-deployment.md` file? Does it still exist under the configuration section? It is not relevant here. Deployment comes after configuration.

2020-11-30 16:17 UTC, j-zimnowoda requested changes
Thanks for a fresh look at our documentation :)
Minor changes requested

2020-11-30 16:17 UTC, j-zimnowoda commented on docs/inst-configuration.md
> +otomi validate-templates && otomi validate-values
otomi validate-values && otomi validate-templates

First we validate values, then populate them to and validate generate templates.
The otomi validate-values is also much faster/

2020-11-30 16:17 UTC, j-zimnowoda commented on docs/inst-deployment.md
> +The CLOUD and CLUSTER environment variables are used to specify the cloud and cluster you wish to target. They are used to specify a directory path in your otomi-values repository. CLOUD should be on
The CLOUD and CLUSTER environment variables are used to specify target cluster configuration.
A cluster configuration is stored in:
- `env/clouds/$CLOUD/$CLUSTER/` directory
- `env/clusters.yaml` file at `clouds.$CLOUD.clusters.$CLUSTER` property

After bootstrapping, the default cloud and cluster are respectively 'google' and 'demo'.

2020-12-01 21:18 UTC, Morriz commented on docs/inst-prerequisites.md
> +- AWS: `aws configure`
I don't agree here, we are not in the business of teaching aws basics.

2020-12-01 21:19 UTC, Morriz commented on docs/inst-setup.md
> +docker run --rm -e ENV_DIR=$PWD -v $PWD:$PWD otomi/core:latest bin/bootstrap.sh
tnx

2020-12-02 00:07 UTC, Morriz commented
Closing this as all good parts have been cherry picked by me and committed in c3c77ad..39d26fe.

Thanks @svatwork and @j-zimnowoda !

2020-12-02 00:07 UTC, closed without merging

2020-12-02 14:11 UTC, svatwork commented on docs/inst-prerequisites.md
> +- AWS: `aws configure`
I modified this because there is no command `aws login eks` (my version anyway):

```
aws --version
aws-cli/2.1.1 Python/3.9.0 Darwin/18.7.0 source/x86_64
```

2020-12-02 14:11 UTC, svatwork commented
> Closing this as all good parts have been cherry picked by me and committed in [c3c77ad](https://github.com/redkubes/otomi/commit/c3c77adfaa46b7729d52a41ea700b8773f96d677)..[39d26fe](https://github.com/redkubes/otomi/commit/39d26feb78db1a5d0ea43f26457f8172b92ad608).
> 
> Thanks @svatwork and @j-zimnowoda !

Noticed, looks good!